services:
  postgres:
    image: postgres:15
    container_name: currency_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: currency_minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  airflow:
    image: apache/airflow:2.8.1-python3.11
    container_name: currency_airflow
    restart: always
    depends_on:
      - postgres
      - minio

    entrypoint: ["/bin/bash", "/opt/airflow/scripts/entrypoint.sh"]

    environment:
      AIRFLOW__CORE__FERNET_KEY: "auto"

      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: "False"

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: "airflow"
      _AIRFLOW_WWW_USER_PASSWORD: "airflow"
      _AIRFLOW_WWW_USER_EMAIL: "admin@example.com"
      _AIRFLOW_WWW_USER_FIRSTNAME: "Admin"
      _AIRFLOW_WWW_USER_LASTNAME: "User"

    ports:
      - "8080:8080"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts

  # -----------------------------
  # STREAMLIT DASHBOARD SERVICE
  # -----------------------------
  streamlit:
    build: ./streamlit_app
    container_name: currency_streamlit
    restart: always
    depends_on:
      - postgres
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app
    environment:
      DATABASE_URL: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

volumes:
  postgres_data:
  minio_data:
